name: iOS Build + Unsigned IPA

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -project siop/SIoP.xcodeproj

      - name: Build app for simulator
        run: |
          xcodebuild \
            -project siop/SIoP.xcodeproj \
            -scheme SIoP \
            -configuration Debug \
            -sdk iphonesimulator \
            -destination 'generic/platform=iOS Simulator' \
            CODE_SIGNING_ALLOWED=NO \
            build

      - name: Find built app
        run: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "SIoP.app" | head -n 1)
          echo "APP_PATH=$APP_PATH" >> $GITHUB_ENV
          echo "$APP_PATH"

      - name: Create Payload folder
        run: |
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/

      - name: Create unsigned IPA
        run: |
          zip -r SIoP-unsigned.ipa Payload

      - name: Upload unsigned IPA
        uses: actions/upload-artifact@v4
        with:
          name: SIoP-unsigned-ipa
          path: SIoP-unsigned.ipa
